# Generated by Django 2.2.1 on 2019-05-08 21:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import model.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to=model.models.upload_file_location)),
                ('model_path', models.FileField(upload_to=model.models.upload_model_location)),
                ('column_info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('train_info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sets', to='project.Project')),
            ],
        ),
    ]
