# Generated by Django 2.2.1 on 2019-05-08 22:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_auto_20190508_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='column_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='train_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
