"""empty message

Revision ID: 0a4e84443ebd
Revises: d37adeed3dd9
Create Date: 2019-03-10 08:09:29.323150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a4e84443ebd'
down_revision = 'd37adeed3dd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dataset_name_key', 'dataset', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('dataset_name_key', 'dataset', ['title'])
    # ### end Alembic commands ###
