"""empty message

Revision ID: 225eaa5480ab
Revises: 826b8424a7ee
Create Date: 2019-05-05 18:28:07.255288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '225eaa5480ab'
down_revision = '826b8424a7ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    # ### end Alembic commands ###
