"""empty message

Revision ID: 826b8424a7ee
Revises: 98020412113a
Create Date: 2019-03-10 09:35:59.678179

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '826b8424a7ee'
down_revision = '98020412113a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('train_info', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset', 'train_info')
    # ### end Alembic commands ###
