"""empty message

Revision ID: 98020412113a
Revises: 0a4e84443ebd
Create Date: 2019-03-10 09:30:05.826761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98020412113a'
down_revision = '0a4e84443ebd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('model_path', sa.String(length=264), nullable=True))
    op.create_unique_constraint(None, 'dataset', ['model_path'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dataset', type_='unique')
    op.drop_column('dataset', 'model_path')
    # ### end Alembic commands ###
